### ISSUE TITLE
API - odbieranie danych z AKAI_MANAGER

### ISSUE THREAD

**Issue by PatrykGrzegorek** [akai-org/proxy_blog#5]
Odbieranie api z akai_magager. I zapisywanie ich. @MichalSz99 możesz bardziej rozpisać, chyba że Ty się zajmiesz tym taskiem.

**Comment by MichalSz99** [comment]
Zrobię to tylko muszę wiedzieć co z tymi zdjęciami i dowiedzieć się jaki jest link do pobrania z AKAI Menagera

**Comment by PatrykGrzegorek** [comment]
Jeszcze linku od nich nie mamy, będzie pewnie dopiero we wtorek :C
